name: ishraqa_app
description: "ØªØ·Ø¨ÙŠÙ‚ Ø¥Ø´Ø±Ø§Ù‚Ø© ÙŠÙˆÙ…ÙŠØ© Ù„Ø¹Ø±Ø¶ Ø§Ù‚ØªØ¨Ø§Ø³Ø§Øª Ù…Ø­ÙÙ‘Ø²Ø© ÙˆÙ…ÙÙŠØ¯Ø©"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0-180.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2
  share_plus: ^7.2.1
  url_launcher: ^6.2.5
  flutter_native_splash: ^2.3.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo_icon.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo_splash.png
  android: true
  ios: true
  web: false
  fullscreen: true

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/logo_splash.png
    - assets/logo_icon.png

# ğŸ› ï¸ Ø§Ù„Ø­Ù„ Ù„Ù„Ù…Ø´ÙƒÙ„Ø© Ø§Ù„Ø­Ø§Ù„ÙŠØ©
dependency_overrides:
  fading_edge_scrollview: ^2.0.0
